// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: guard.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const beginApprovalExecution = `-- name: BeginApprovalExecution :one
UPDATE approvals
SET execution_status = 'executing', execution_started_at = now(), execution_completed_at = NULL,
    execution_error = '', execution_lease_until = now() + interval '2 minutes',
    execution_attempts = execution_attempts + 1, execution_token = $1
WHERE id = $2
  AND conversation_id = $3
  AND status = 'approved'
  AND execution_attempts < 5
  AND (
      execution_status = 'not_started'
      OR execution_status = 'failed'
      OR (execution_status = 'executing' AND execution_lease_until < now())
  )
RETURNING id, conversation_id, action, payload, status, approver_id, created_at, resolved_at, workspace_id, execution_status, execution_started_at, execution_completed_at, execution_error, execution_lease_until, execution_attempts, execution_token
`

type BeginApprovalExecutionParams struct {
	ExecutionToken pgtype.UUID
	ID             uuid.UUID
	ConversationID pgtype.UUID
}

func (q *Queries) BeginApprovalExecution(ctx context.Context, arg BeginApprovalExecutionParams) (Approval, error) {
	row := q.db.QueryRow(ctx, beginApprovalExecution, arg.ExecutionToken, arg.ID, arg.ConversationID)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Action,
		&i.Payload,
		&i.Status,
		&i.ApproverID,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.WorkspaceID,
		&i.ExecutionStatus,
		&i.ExecutionStartedAt,
		&i.ExecutionCompletedAt,
		&i.ExecutionError,
		&i.ExecutionLeaseUntil,
		&i.ExecutionAttempts,
		&i.ExecutionToken,
	)
	return i, err
}

const completeApprovalExecution = `-- name: CompleteApprovalExecution :execrows
UPDATE approvals
SET execution_status = 'completed', execution_completed_at = now(), execution_error = '',
    execution_lease_until = NULL, execution_token = NULL
WHERE id = $1 AND execution_status = 'executing'
  AND execution_token = $2
`

type CompleteApprovalExecutionParams struct {
	ID             uuid.UUID
	ExecutionToken pgtype.UUID
}

func (q *Queries) CompleteApprovalExecution(ctx context.Context, arg CompleteApprovalExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeApprovalExecution, arg.ID, arg.ExecutionToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createApproval = `-- name: CreateApproval :one

INSERT INTO approvals (id, workspace_id, conversation_id, action, payload, status, created_at)
VALUES ($1, $2, $3, $4, $5, 'pending', now())
RETURNING id, conversation_id, action, payload, status, approver_id, created_at, resolved_at, workspace_id, execution_status, execution_started_at, execution_completed_at, execution_error, execution_lease_until, execution_attempts, execution_token
`

type CreateApprovalParams struct {
	ID             uuid.UUID
	WorkspaceID    string
	ConversationID pgtype.UUID
	Action         string
	Payload        []byte
}

// 人在环审批。
func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, createApproval,
		arg.ID,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.Action,
		arg.Payload,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Action,
		&i.Payload,
		&i.Status,
		&i.ApproverID,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.WorkspaceID,
		&i.ExecutionStatus,
		&i.ExecutionStartedAt,
		&i.ExecutionCompletedAt,
		&i.ExecutionError,
		&i.ExecutionLeaseUntil,
		&i.ExecutionAttempts,
		&i.ExecutionToken,
	)
	return i, err
}

const failApprovalExecution = `-- name: FailApprovalExecution :execrows
UPDATE approvals
SET execution_status = 'failed', execution_completed_at = now(), execution_error = $1,
    execution_lease_until = NULL, execution_token = NULL
WHERE id = $2 AND execution_status = 'executing'
  AND execution_token = $3
`

type FailApprovalExecutionParams struct {
	ExecutionError string
	ID             uuid.UUID
	ExecutionToken pgtype.UUID
}

func (q *Queries) FailApprovalExecution(ctx context.Context, arg FailApprovalExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, failApprovalExecution, arg.ExecutionError, arg.ID, arg.ExecutionToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApproval = `-- name: GetApproval :one
SELECT id, conversation_id, action, payload, status, approver_id, created_at, resolved_at, workspace_id, execution_status, execution_started_at, execution_completed_at, execution_error, execution_lease_until, execution_attempts, execution_token FROM approvals WHERE id = $1 LIMIT 1
`

func (q *Queries) GetApproval(ctx context.Context, id uuid.UUID) (Approval, error) {
	row := q.db.QueryRow(ctx, getApproval, id)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Action,
		&i.Payload,
		&i.Status,
		&i.ApproverID,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.WorkspaceID,
		&i.ExecutionStatus,
		&i.ExecutionStartedAt,
		&i.ExecutionCompletedAt,
		&i.ExecutionError,
		&i.ExecutionLeaseUntil,
		&i.ExecutionAttempts,
		&i.ExecutionToken,
	)
	return i, err
}

const listApprovalsByConversation = `-- name: ListApprovalsByConversation :many
SELECT id, conversation_id, action, payload, status, approver_id, created_at, resolved_at, workspace_id, execution_status, execution_started_at, execution_completed_at, execution_error, execution_lease_until, execution_attempts, execution_token FROM approvals WHERE conversation_id = $1 ORDER BY created_at
`

func (q *Queries) ListApprovalsByConversation(ctx context.Context, conversationID pgtype.UUID) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listApprovalsByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Action,
			&i.Payload,
			&i.Status,
			&i.ApproverID,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.WorkspaceID,
			&i.ExecutionStatus,
			&i.ExecutionStartedAt,
			&i.ExecutionCompletedAt,
			&i.ExecutionError,
			&i.ExecutionLeaseUntil,
			&i.ExecutionAttempts,
			&i.ExecutionToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovals = `-- name: ListPendingApprovals :many
SELECT id, conversation_id, action, payload, status, approver_id, created_at, resolved_at, workspace_id, execution_status, execution_started_at, execution_completed_at, execution_error, execution_lease_until, execution_attempts, execution_token FROM approvals
WHERE workspace_id = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingApprovals(ctx context.Context, workspaceID string) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listPendingApprovals, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Action,
			&i.Payload,
			&i.Status,
			&i.ApproverID,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.WorkspaceID,
			&i.ExecutionStatus,
			&i.ExecutionStartedAt,
			&i.ExecutionCompletedAt,
			&i.ExecutionError,
			&i.ExecutionLeaseUntil,
			&i.ExecutionAttempts,
			&i.ExecutionToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyApprovalResumes = `-- name: ListReadyApprovalResumes :many
SELECT id, conversation_id, action, payload, status, approver_id, created_at, resolved_at, workspace_id, execution_status, execution_started_at, execution_completed_at, execution_error, execution_lease_until, execution_attempts, execution_token FROM approvals
WHERE status = 'approved'
  AND execution_attempts < 5
  AND (
      execution_status = 'not_started'
      OR execution_status = 'failed'
      OR (execution_status = 'executing' AND execution_lease_until < now())
  )
ORDER BY resolved_at ASC
LIMIT $1
`

func (q *Queries) ListReadyApprovalResumes(ctx context.Context, limit int32) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listReadyApprovalResumes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Action,
			&i.Payload,
			&i.Status,
			&i.ApproverID,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.WorkspaceID,
			&i.ExecutionStatus,
			&i.ExecutionStartedAt,
			&i.ExecutionCompletedAt,
			&i.ExecutionError,
			&i.ExecutionLeaseUntil,
			&i.ExecutionAttempts,
			&i.ExecutionToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewApprovalExecution = `-- name: RenewApprovalExecution :execrows
UPDATE approvals
SET execution_lease_until = now() + interval '2 minutes'
WHERE id = $1
  AND execution_status = 'executing'
  AND execution_token = $2
`

type RenewApprovalExecutionParams struct {
	ID             uuid.UUID
	ExecutionToken pgtype.UUID
}

func (q *Queries) RenewApprovalExecution(ctx context.Context, arg RenewApprovalExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewApprovalExecution, arg.ID, arg.ExecutionToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolvePendingApproval = `-- name: ResolvePendingApproval :one
WITH resolved AS (
    UPDATE approvals
    SET status = $1, approver_id = $2, resolved_at = now()
    WHERE approvals.id = $3
      AND approvals.workspace_id = $4
      AND status = 'pending'
    RETURNING id, conversation_id, action, payload, status, approver_id, created_at, resolved_at, workspace_id, execution_status, execution_started_at, execution_completed_at, execution_error, execution_lease_until, execution_attempts, execution_token
), released AS (
    UPDATE conversations
    SET status = 'active', updated_at = now()
    WHERE id = (SELECT conversation_id FROM resolved)
      AND (SELECT status FROM resolved) = 'rejected'
      AND status = 'awaiting_approval'
)
SELECT approvals.id, approvals.conversation_id, approvals.action, approvals.payload, approvals.status, approvals.approver_id, approvals.created_at, approvals.resolved_at, approvals.workspace_id, approvals.execution_status, approvals.execution_started_at, approvals.execution_completed_at, approvals.execution_error, approvals.execution_lease_until, approvals.execution_attempts, approvals.execution_token
FROM approvals
JOIN resolved ON resolved.id = approvals.id
`

type ResolvePendingApprovalParams struct {
	TargetStatus      string
	ActorID           pgtype.UUID
	ApprovalID        uuid.UUID
	TargetWorkspaceID string
}

func (q *Queries) ResolvePendingApproval(ctx context.Context, arg ResolvePendingApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, resolvePendingApproval,
		arg.TargetStatus,
		arg.ActorID,
		arg.ApprovalID,
		arg.TargetWorkspaceID,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Action,
		&i.Payload,
		&i.Status,
		&i.ApproverID,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.WorkspaceID,
		&i.ExecutionStatus,
		&i.ExecutionStartedAt,
		&i.ExecutionCompletedAt,
		&i.ExecutionError,
		&i.ExecutionLeaseUntil,
		&i.ExecutionAttempts,
		&i.ExecutionToken,
	)
	return i, err
}
