// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID          uuid.UUID
	WorkspaceID string
	Name        string
	Template    string
	Description string
	CreatedBy   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type AgentEnv struct {
	AgentID   uuid.UUID
	Env       string
	VersionID uuid.UUID
	UpdatedAt time.Time
}

type AgentVersion struct {
	ID           uuid.UUID
	AgentID      uuid.UUID
	Version      int32
	SnapshotJson string
	CreatedBy    string
	CreatedAt    time.Time
}

type ApiKey struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Scopes     []string
	Hash       string
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  time.Time
}

type Approval struct {
	ID                   uuid.UUID
	ConversationID       pgtype.UUID
	Action               string
	Payload              []byte
	Status               string
	ApproverID           pgtype.UUID
	CreatedAt            time.Time
	ResolvedAt           pgtype.Timestamptz
	WorkspaceID          string
	ExecutionStatus      string
	ExecutionStartedAt   pgtype.Timestamptz
	ExecutionCompletedAt pgtype.Timestamptz
	ExecutionError       string
	ExecutionLeaseUntil  pgtype.Timestamptz
	ExecutionAttempts    int32
	ExecutionToken       pgtype.UUID
}

type AuditLog struct {
	ID           int64
	Actor        string
	Action       string
	ResourceType string
	ResourceID   string
	BeforeJson   pgtype.Text
	AfterJson    pgtype.Text
	Ip           pgtype.Text
	Ua           pgtype.Text
	CreatedAt    time.Time
	WorkspaceID  string
}

type AuditLogsDefault struct {
	ID           int64
	Actor        string
	Action       string
	ResourceType string
	ResourceID   string
	BeforeJson   pgtype.Text
	AfterJson    pgtype.Text
	Ip           pgtype.Text
	Ua           pgtype.Text
	CreatedAt    time.Time
}

type Checkpoint struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	StateSnapshot  []byte
	CreatedAt      time.Time
	ApprovalID     pgtype.UUID
}

type ConnectorInstance struct {
	ID            uuid.UUID
	KbID          uuid.UUID
	ConnectorKind string
	ConfigJson    string
	Cursor        string
	LastSyncAt    pgtype.Timestamptz
	CreatedAt     time.Time
}

type Conversation struct {
	ID             uuid.UUID
	AgentID        string
	AgentVersionID string
	UserID         string
	WorkspaceID    string
	Classification string
	Status         string
	StartedAt      time.Time
	UpdatedAt      time.Time
	TurnToken      pgtype.UUID
	TurnLeaseUntil pgtype.Timestamptz
	TurnRevision   int64
}

type ConversationRuntimeConfig struct {
	ConversationID uuid.UUID
	ConfigJson     []byte
	CreatedAt      time.Time
}

type DeadLetter struct {
	ID      uuid.UUID
	JobID   pgtype.UUID
	Payload []byte
	Error   string
	DlqAt   time.Time
}

type Job struct {
	ID             uuid.UUID
	WorkspaceID    string
	Type           string
	Payload        []byte
	Status         string
	Attempts       int32
	ScheduledAt    pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	Error          string
	IdempotencyKey pgtype.Text
}

type JobSchedule struct {
	ID        uuid.UUID
	Type      string
	Payload   []byte
	Cron      string
	NextRunAt pgtype.Timestamptz
	Enabled   bool
}

type Kb struct {
	ID             uuid.UUID
	WorkspaceID    string
	Name           string
	ChunkingConfig string
	EmbeddingModel string
	Status         string
	CreatedBy      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type KbChunk struct {
	ID                uuid.UUID
	KbID              uuid.UUID
	DocID             uuid.UUID
	Ordinal           int32
	Content           string
	Embedding         interface{}
	Classification    string
	Metadata          []byte
	CreatedAt         time.Time
	SearchText        string
	Tsv               interface{}
	EmbeddingIdentity string
}

type KbDocument struct {
	ID                uuid.UUID
	KbID              uuid.UUID
	SourceType        string
	SourceUri         string
	Hash              string
	Classification    string
	Status            string
	IngestedAt        pgtype.Timestamptz
	CreatedAt         time.Time
	EmbeddingIdentity string
}

type KbIngestJob struct {
	ID         uuid.UUID
	KbID       uuid.UUID
	DocID      uuid.UUID
	Stage      string
	Retries    int32
	Error      pgtype.Text
	StartedAt  time.Time
	FinishedAt pgtype.Timestamptz
}

type Message struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	Role           string
	Content        string
	ToolCalls      []byte
	ToolCallID     pgtype.Text
	CreatedAt      time.Time
}

type ModelCallLog struct {
	ID                   uuid.UUID
	AgentID              pgtype.UUID
	UserID               pgtype.UUID
	Model                string
	InputTokens          int32
	OutputTokens         int32
	CachedTokens         int32
	Cost                 pgtype.Numeric
	LatencyMs            int32
	Status               string
	Classification       string
	CreatedAt            time.Time
	WorkspaceID          string
	PromptVersionID      pgtype.UUID
	ModelConfigVersionID pgtype.UUID
}

type ModelCallLogsDefault struct {
	ID             uuid.UUID
	AgentID        pgtype.UUID
	UserID         pgtype.UUID
	ProviderID     pgtype.UUID
	Model          string
	InputTokens    int32
	OutputTokens   int32
	CachedTokens   int32
	Cost           pgtype.Numeric
	LatencyMs      int32
	Status         string
	Classification string
	CreatedAt      time.Time
}

type ModelConfigVersion struct {
	ID                         uuid.UUID
	WorkspaceID                string
	Name                       string
	Version                    int32
	ProviderKind               string
	BaseUrl                    string
	ModelName                  string
	CredentialRef              string
	TimeoutMs                  int32
	MaxRetries                 int32
	InputPricePerMillion       pgtype.Numeric
	OutputPricePerMillion      pgtype.Numeric
	CachedInputPricePerMillion pgtype.Numeric
	CreatedBy                  string
	CreatedAt                  time.Time
}

type Prompt struct {
	ID          uuid.UUID
	WorkspaceID string
	Name        string
	Category    string
	CreatedBy   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PromptEnv struct {
	PromptID  uuid.UUID
	Env       string
	VersionID uuid.UUID
	UpdatedAt time.Time
}

type PromptVersion struct {
	ID              uuid.UUID
	PromptID        uuid.UUID
	Version         int32
	Template        string
	VariablesSchema string
	Hash            string
	TokenEstimate   int32
	CreatedBy       string
	CreatedAt       time.Time
}

type PromptVersionConfig struct {
	PromptVersionID      uuid.UUID
	ModelConfigVersionID pgtype.UUID
	GenerationConfig     []byte
}

type Role struct {
	ID          uuid.UUID
	Name        string
	Permissions []string
	CreatedAt   time.Time
}

type RolePermission struct {
	Role     string
	Resource string
	Action   string
}

type Skill struct {
	ID          uuid.UUID
	WorkspaceID string
	Name        string
	Category    string
	CreatedBy   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SkillSubscription struct {
	ID          int64
	SkillID     uuid.UUID
	VersionID   uuid.UUID
	AgentID     string
	WorkspaceID string
	CreatedAt   time.Time
}

type SkillTrigger struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	SkillVersionID pgtype.UUID
	TriggeredAt    time.Time
	Success        bool
	WorkspaceID    string
	SkillName      string
	Source         string
}

type SkillVersion struct {
	ID              uuid.UUID
	SkillID         uuid.UUID
	Version         int32
	FrontmatterJson string
	BodyMd          string
	Status          string
	CreatedBy       string
	CreatedAt       time.Time
}

type Tool struct {
	ID          uuid.UUID
	WorkspaceID string
	Name        string
	Description string
	SourceType  string
	Sensitive   bool
	CreatedBy   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ToolCall struct {
	ID            uuid.UUID
	MessageID     uuid.UUID
	ToolID        pgtype.UUID
	ToolVersionID pgtype.UUID
	Args          []byte
	Result        []byte
	LatencyMs     int32
	Error         string
	CreatedAt     time.Time
}

type ToolInvocation struct {
	ID             uuid.UUID
	ConversationID pgtype.UUID
	ToolVersionID  pgtype.UUID
	Args           []byte
	Result         []byte
	LatencyMs      int32
	Error          string
	CreatedAt      time.Time
	WorkspaceID    string
	ToolCallID     string
	Status         string
}

type ToolTestRun struct {
	ID            uuid.UUID
	ToolID        uuid.UUID
	Input         string
	Output        string
	Status        string
	LatencyMs     int32
	Error         pgtype.Text
	CreatedAt     time.Time
	ToolVersionID uuid.UUID
}

type ToolVersion struct {
	ID                  uuid.UUID
	ToolID              uuid.UUID
	Version             int32
	SchemaJson          string
	EndpointConfig      string
	AuthConfig          string
	RetryPolicy         string
	Status              string
	CreatedBy           string
	CreatedAt           time.Time
	AuthConfigEncrypted []byte
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	Role         string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserRole struct {
	UserID      uuid.UUID
	RoleID      uuid.UUID
	WorkspaceID string
}

type Workspace struct {
	ID          string
	Name        string
	Description string
	ParentID    pgtype.Text
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type WorkspaceMember struct {
	WorkspaceID string
	UserID      uuid.UUID
	Role        string
	CreatedAt   time.Time
}
