// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: prompt.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createPrompt = `-- name: CreatePrompt :one
INSERT INTO prompts (id, workspace_id, name, category, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
RETURNING id, workspace_id, name, category, created_by, created_at, updated_at
`

type CreatePromptParams struct {
	ID          uuid.UUID
	WorkspaceID string
	Name        string
	Category    string
	CreatedBy   string
}

func (q *Queries) CreatePrompt(ctx context.Context, arg CreatePromptParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, createPrompt,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Category,
		arg.CreatedBy,
	)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Category,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPromptVersion = `-- name: CreatePromptVersion :one
INSERT INTO prompt_versions (id, prompt_id, version, template, variables_schema, hash, token_estimate, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
RETURNING id, prompt_id, version, template, variables_schema, hash, token_estimate, created_by, created_at
`

type CreatePromptVersionParams struct {
	ID              uuid.UUID
	PromptID        uuid.UUID
	Version         int32
	Template        string
	VariablesSchema string
	Hash            string
	TokenEstimate   int32
	CreatedBy       string
}

func (q *Queries) CreatePromptVersion(ctx context.Context, arg CreatePromptVersionParams) (PromptVersion, error) {
	row := q.db.QueryRow(ctx, createPromptVersion,
		arg.ID,
		arg.PromptID,
		arg.Version,
		arg.Template,
		arg.VariablesSchema,
		arg.Hash,
		arg.TokenEstimate,
		arg.CreatedBy,
	)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.Version,
		&i.Template,
		&i.VariablesSchema,
		&i.Hash,
		&i.TokenEstimate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPrompt = `-- name: GetPrompt :one

SELECT id, workspace_id, name, category, created_by, created_at, updated_at FROM prompts WHERE id = $1 LIMIT 1
`

// Prompt:不可变模板版本。发布由 AgentEnv 统一管理。
func (q *Queries) GetPrompt(ctx context.Context, id uuid.UUID) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPrompt, id)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Category,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptVersion = `-- name: GetPromptVersion :one
SELECT id, prompt_id, version, template, variables_schema, hash, token_estimate, created_by, created_at FROM prompt_versions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPromptVersion(ctx context.Context, id uuid.UUID) (PromptVersion, error) {
	row := q.db.QueryRow(ctx, getPromptVersion, id)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.Version,
		&i.Template,
		&i.VariablesSchema,
		&i.Hash,
		&i.TokenEstimate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptVersionByNumber = `-- name: GetPromptVersionByNumber :one
SELECT id, prompt_id, version, template, variables_schema, hash, token_estimate, created_by, created_at FROM prompt_versions WHERE prompt_id = $1 AND version = $2 LIMIT 1
`

type GetPromptVersionByNumberParams struct {
	PromptID uuid.UUID
	Version  int32
}

func (q *Queries) GetPromptVersionByNumber(ctx context.Context, arg GetPromptVersionByNumberParams) (PromptVersion, error) {
	row := q.db.QueryRow(ctx, getPromptVersionByNumber, arg.PromptID, arg.Version)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.Version,
		&i.Template,
		&i.VariablesSchema,
		&i.Hash,
		&i.TokenEstimate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPromptVersions = `-- name: ListPromptVersions :many
SELECT id, prompt_id, version, template, variables_schema, hash, token_estimate, created_by, created_at FROM prompt_versions WHERE prompt_id = $1 ORDER BY version
`

func (q *Queries) ListPromptVersions(ctx context.Context, promptID uuid.UUID) ([]PromptVersion, error) {
	rows, err := q.db.Query(ctx, listPromptVersions, promptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromptVersion{}
	for rows.Next() {
		var i PromptVersion
		if err := rows.Scan(
			&i.ID,
			&i.PromptID,
			&i.Version,
			&i.Template,
			&i.VariablesSchema,
			&i.Hash,
			&i.TokenEstimate,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrompts = `-- name: ListPrompts :many
SELECT id, workspace_id, name, category, created_by, created_at, updated_at FROM prompts WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) ListPrompts(ctx context.Context, workspaceID string) ([]Prompt, error) {
	rows, err := q.db.Query(ctx, listPrompts, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prompt{}
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Category,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
